import React from "react";
import Head from "next/head";

const Author: React.FC = () => {
  return (
    <div className=" min-h-screen py-12 px-6">
      <Head>
        <title>Hello, World.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-3xl mx-auto text-center">
        {/* キャラクター画像 */}
        <img
          className="w-3/6 mx-auto mb-8"
          src="animal_chara_computer_azarashi.png"
          alt="アザラシのキャラクター"
        />

        {/* 著者名 */}
        <h1 className="text-4xl font-extrabold text-gray-800">
          Author's Name: Hello, World.
        </h1>

        {/* 自己紹介メッセージ */}
        <p className="mt-6 text-lg text-gray-600 leading-relaxed">
          人間。このブログでは主にプログラミングや趣味のことについて書こうと思います。
        </p>

        <p className="mt-4 text-lg text-gray-600 leading-relaxed">
          好きなボカロPは<span className="font-semibold text-gray-800">日向電工</span>と
          <span className="font-semibold text-gray-800">wowaka</span>。
          使用プログラミング言語は
          <span className="font-semibold text-blue-600">TypeScript</span>
          と
          <span className="font-semibold text-blue-600">JavaScript</span>。
        </p>
      </div>
    </div>
  );
};

export default Author;
